### ISSUE TITLE
openenclave-src/host/sgx/create.c:_initialize_enclave:488 

### ISSUE THREAD

**Issue by aep** [edgelesssys/edgelessrt#113]
how would i get more debug info out of erthost?

```
/opt/edgelessrt/bin/erthost coordinator-enclave.signed
[erthost] loading enclave ...                                                                              
ERROR: :OE_FAILURE [openenclave-src/host/sgx/create.c:_initialize_enclave:488]
ERROR: oe_create_enclave failed. (Set OE_SIMULATION=1 for simulation mode.) [src/tools/erthost/erthost.cpp:main:265]
```

this is with https://github.com/edgelesssys/edgelessrt/releases/tag/v0.3.2
and https://github.com/edgelesssys/marblerun/releases/tag/v0.5.1

**Comment by thomasten** [comment]
try these env vars https://github.com/edgelesssys/edgelessrt#logging

**Comment by aep** [comment]
this does not happen when building ert and marblerun from source. everything works fine now.
is the binary release outdated maybe?

**Comment by thomasten** [comment]
> this is with https://github.com/edgelesssys/edgelessrt/releases/tag/v0.3.2
> and https://github.com/edgelesssys/marblerun/releases/tag/v0.5.1

Sorry, I didn't pay attention to this. The version of erthost must match the ERT version used to build the enclave. That's why we add the erthost executable to the MarbleRun binary release. So you can either use both binaries from the MR release or you can use the ERT binary release and build MR from source. (Of course you can always build both from source.)

**Comment by aep** [comment]
oh! that explains it. thank you.
