### ISSUE TITLE
coredump in sample:go_ra (v0.2.5)

### ISSUE THREAD

**Issue by cjqpker** [edgelesssys/edgelessrt#75]
### Issue description
Remote attestation failed in sample "go_ra"  (version v0.2.5)

### To reproduce

1. Follow "Quick Start" in ubuntu18.04 docker container
2. Install dcap components following [openenclave](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md)
3. Run container with --device /dev/sgx
4. Build sample go_ra
5. Run `erthost enclave.signed` and got coredump

### Expected behavior
It works fine in version v0.2.3

### Additional info / screenshot
![Screen Shot 2021-07-28 at 11 05 30](https://user-images.githubusercontent.com/14192091/127257260-dea04a41-25d8-4888-8961-30126c7b8b61.png)

**Comment by daniel-weisse** [comment]
Hi @cjqpker from my experience this is caused by missing intel sgx libraries.
We provide docker images for Edgeless RT which include all the necessary libraries, and recently got updated to include `libsgx-dcap-default-qpl` so they can be used without Azure infrastructure: https://github.com/edgelesssys/edgelessrt/pkgs/container/edgelessrt-dev (the nightly release includes the changes)

If you want to use this image, make sure to remove `az-dcap-client` as describe in https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md
and create the link:
```bash
ln -s /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1.intel /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so
```

Otherwise adding the necessary libraries should fix the issue, you can take a look at [our Dockerfile](https://github.com/edgelesssys/edgelessrt/blob/master/Dockerfile#L19) for a reference.

Also make sure to set the correct values for your PCCS in `/etc/sgx_default_qcnl.conf` .

**Comment by cjqpker** [comment]
Thanks @daniel-weisse 
I ran container with image ghcr.io/edgelesssys/edgelessrt-dev:v0.2.5 and rebuilt go_ra, but got the same coredump when executing `erthost enclave.signed`.
After that, I test v0.2.3 and v0.2.4 using my docker image and both work fine

BTW，versions of PSW(2.14.100.2) and DCAP(1.11.100.2) upgraded since v0.2.4

**Comment by daniel-weisse** [comment]
I am not totally sure, but i suspect the problem coming from some incompatibility with dependencies installed by the packaged ert v0.2.5 release.

Could you please check if the nightly image works for you?
Set up should work something like the following:
```bash
# download and run the image
docker pull ghcr.io/edgelesssys/edgelessrt-dev:nightly
docker run -it --device /dev/sgx --network host --rm ghcr.io/edgelesssys/edgelessrt-dev:nightly

# backup az-dcap-client library
mv /usr/lib/libdcap_quoteprov.so /usr/lib/libdcap_quoteprov.so.azure

# restore intel library and create link
mv /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1.intel /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1
ln -s /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1 /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so

# configure /etc/sgx_default_qcnl.conf
# point PCCS_URL to your PCCS and set USE_SECURE_CERT to TRUE/FALSE depending on if you use self signed certs or not
vim /etc/sgx_default_qcnl.conf

# build the sample
git clone https://github.com/edgelesssys/edgelessrt
mkdir edgelessrt/samples/go_ra/build && cd edgelessrt/samples/go_ra/build
cmake .. && make

# run the sample
erthost enclave.signed
```

**Comment by cjqpker** [comment]
@daniel-weisse nightly image works fine, thanks
